# Imagem base
FROM node:22

# Diretório de trabalho
WORKDIR /app

# Copiar ficheiros de dependências
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o resto do código
COPY . .

# Porta da API de dados
EXPOSE 16025

# Ficheiro principal da API
CMD ["node", "app.js"]
